// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package filesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmFileUpload = `-- name: ConfirmFileUpload :one
UPDATE files
SET
  status = $2,
  uploaded_at = CASE
    WHEN $2 = 'FILE_STATUS_AVAILABLE' THEN $3
    ELSE uploaded_at
  END,
  updated_at = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, original_name, storage_path, mime_type, size_bytes, checksum, service_origin, is_public, status, storage_provider, uploaded_by, uploaded_at, created_at, updated_at, deleted_at
`

type ConfirmFileUploadParams struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ConfirmFileUpload(ctx context.Context, arg ConfirmFileUploadParams) (File, error) {
	row := q.db.QueryRow(ctx, confirmFileUpload, arg.ID, arg.Status, arg.UpdatedAt)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.ServiceOrigin,
		&i.IsPublic,
		&i.Status,
		&i.StorageProvider,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
  id,
  original_name,
  storage_path,
  mime_type,
  size_bytes,
  checksum,
  service_origin,
  is_public,
  status,
  storage_provider,
  uploaded_by,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12
)
RETURNING id, original_name, storage_path, mime_type, size_bytes, checksum, service_origin, is_public, status, storage_provider, uploaded_by, uploaded_at, created_at, updated_at, deleted_at
`

type CreateFileParams struct {
	ID              pgtype.UUID        `json:"id"`
	OriginalName    string             `json:"original_name"`
	StoragePath     string             `json:"storage_path"`
	MimeType        string             `json:"mime_type"`
	SizeBytes       int64              `json:"size_bytes"`
	Checksum        string             `json:"checksum"`
	ServiceOrigin   string             `json:"service_origin"`
	IsPublic        bool               `json:"is_public"`
	Status          string             `json:"status"`
	StorageProvider string             `json:"storage_provider"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.OriginalName,
		arg.StoragePath,
		arg.MimeType,
		arg.SizeBytes,
		arg.Checksum,
		arg.ServiceOrigin,
		arg.IsPublic,
		arg.Status,
		arg.StorageProvider,
		arg.UploadedBy,
		arg.CreatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.ServiceOrigin,
		&i.IsPublic,
		&i.Status,
		&i.StorageProvider,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, original_name, storage_path, mime_type, size_bytes, checksum, service_origin, is_public, status, storage_provider, uploaded_by, uploaded_at, created_at, updated_at, deleted_at
FROM files
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.ServiceOrigin,
		&i.IsPublic,
		&i.Status,
		&i.StorageProvider,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
