// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package filesdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID              pgtype.UUID        `json:"id"`
	OriginalName    string             `json:"original_name"`
	StoragePath     string             `json:"storage_path"`
	MimeType        string             `json:"mime_type"`
	SizeBytes       int64              `json:"size_bytes"`
	Checksum        string             `json:"checksum"`
	ServiceOrigin   string             `json:"service_origin"`
	IsPublic        bool               `json:"is_public"`
	Status          string             `json:"status"`
	StorageProvider string             `json:"storage_provider"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	UploadedAt      pgtype.Timestamptz `json:"uploaded_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
